version: '3.8'

networks:
  nukerduit:
    driver: bridge

services:
    # Web Server Service
    nginx:
      image: nginx:alpine
      container_name: nginx
      ports:
        - "8080:80"
      volumes:
        - ./backend:/var/www
        - ./nginx/conf.d/:/etc/nginx/conf.d/
      depends_on:
        - backend_app
      networks:
        - nukerduit

    db:
      image: postgres:latest
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
      ports:
        - "5432:5432"
      networks:
        - nukerduit

    # Application Service
    backend_app:
      container_name: backend
      build: 
        context: ./backend
        dockerfile: Dockerfile
      environment:
        - DB_HOST=db
        - DB_CONNECTION=pgsql
        - DB_PORT=5432
        - DB_DATABASE=postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=root
      volumes:
        - ./backend:/var/www
      ports:
        - "9000:9000"
      working_dir: /var/www
      depends_on:
        - db
      networks:
        - nukerduit